prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/menú_de_navegación_de_escritorio.sql
@@application/shared_components/navigation/lists/barra_de_navegación_de_escritorio.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/shared_components/files/menu_ajuste_png.sql
@@application/shared_components/files/menu_ajuste2_png.sql
@@application/shared_components/files/menu_ayuda1_png.sql
@@application/shared_components/files/menu_ayuda2_png.sql
@@application/shared_components/files/menu_cobro_png.sql
@@application/shared_components/files/menu_compra1_png.sql
@@application/shared_components/files/menu_compra2_png.sql
@@application/shared_components/files/menu_compra3_png.sql
@@application/shared_components/files/menu_compra4_png.sql
@@application/shared_components/files/menu_compra5_png.sql
@@application/shared_components/files/menu_pago_png.sql
@@application/shared_components/files/menu_referencias_png.sql
@@application/shared_components/files/menu_referencias2_png.sql
@@application/shared_components/files/menu_stock1_png.sql
@@application/shared_components/files/menu_stock2_png.sql
@@application/shared_components/files/menu_stock3_png.sql
@@application/shared_components/files/menu_stock4_png.sql
@@application/shared_components/files/menu_stock5_png.sql
@@application/shared_components/files/menu_venta1_png.sql
@@application/shared_components/files/menu_venta2_png.sql
@@application/shared_components/files/menu_venta3_png.sql
@@application/shared_components/files/menu_venta4_png.sql
@@application/shared_components/files/prueba_png.sql
@@application/shared_components/files/prueba2_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/derechos_de_administración.sql
@@application/shared_components/security/authorizations/menu_inicio.sql
@@application/shared_components/security/authorizations/menu_referencias_del_sistema.sql
@@application/shared_components/security/authorizations/acceso_paginas.sql
@@application/shared_components/security/authorizations/boton_crear.sql
@@application/shared_components/security/authorizations/boton_modificar.sql
@@application/shared_components/security/authorizations/boton_eliminar.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/set_report_url.sql
@@application/shared_components/logic/application_processes/set_report_url_descargar.sql
@@application/shared_components/logic/application_items/report_base_url.sql
@@application/shared_components/logic/application_items/report_base_url_rest.sql
@@application/shared_components/logic/application_items/report_format.sql
@@application/shared_components/logic/application_items/report_pass.sql
@@application/shared_components/logic/application_items/report_user.sql
@@application/shared_components/logic/application_computations/report_base_url.sql
@@application/shared_components/logic/application_computations/report_base_url_rest.sql
@@application/shared_components/logic/application_computations/report_format.sql
@@application/shared_components/logic/application_computations/report_pass.sql
@@application/shared_components/logic/application_computations/report_user.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/lov_acc_grupo.sql
@@application/shared_components/user_interface/lovs/lov_art_existencias.sql
@@application/shared_components/user_interface/lovs/lov_articulos.sql
@@application/shared_components/user_interface/lovs/lov_cat_articulos.sql
@@application/shared_components/user_interface/lovs/lov_ciudades.sql
@@application/shared_components/user_interface/lovs/lov_clientes.sql
@@application/shared_components/user_interface/lovs/lov_cobradores.sql
@@application/shared_components/user_interface/lovs/lov_con_ventas.sql
@@application/shared_components/user_interface/lovs/lov_depositos.sql
@@application/shared_components/user_interface/lovs/lov_distrito.sql
@@application/shared_components/user_interface/lovs/lov_empresas.sql
@@application/shared_components/user_interface/lovs/lov_est_articulos.sql
@@application/shared_components/user_interface/lovs/lov_est_civil.sql
@@application/shared_components/user_interface/lovs/lov_est_clientes.sql
@@application/shared_components/user_interface/lovs/lov_est_comprobantes.sql
@@application/shared_components/user_interface/lovs/lov_est_usuarios.sql
@@application/shared_components/user_interface/lovs/lov_exist_art_transaccion.sql
@@application/shared_components/user_interface/lovs/lov_iva.sql
@@application/shared_components/user_interface/lovs/lov_monedas.sql
@@application/shared_components/user_interface/lovs/lov_paises.sql
@@application/shared_components/user_interface/lovs/lov_personas.sql
@@application/shared_components/user_interface/lovs/lov_proveedores.sql
@@application/shared_components/user_interface/lovs/lov_provincias.sql
@@application/shared_components/user_interface/lovs/lov_rol_item.sql
@@application/shared_components/user_interface/lovs/lov_sucursales.sql
@@application/shared_components/user_interface/lovs/lov_tip_clientes.sql
@@application/shared_components/user_interface/lovs/lov_tip_comprobantes.sql
@@application/shared_components/user_interface/lovs/lov_tip_documentos.sql
@@application/shared_components/user_interface/lovs/lov_tip_segmentos.sql
@@application/shared_components/user_interface/lovs/lov_tip_vin_personas.sql
@@application/shared_components/user_interface/lovs/lov_uni_med_articulo.sql
@@application/shared_components/user_interface/lovs/lov_vendedores.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/modal_dialog2.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/theme_display_points.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/autenticación_de_application_express.sql
@@application/shared_components/security/authentications/custom_auth.sql
@@application/shared_components/plugins/item_type/si_trts_autonumeric.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00100.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
